eureka:
  client:
    service-url:
      defaultZone: https://eureka-service.onrender.com/eureka/

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOriginPatterns:
              - "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
            allowedHeaders:
              - "*"
            exposedHeaders:
              - "Authorization"
            allowCredentials: true
      routes:
        - id: EVENTS
          uri: lb://EVENTS
          predicates:
            - Path=/api/events/**
        - id: NOTIFICATIONS
          uri: lb://NOTIFICATIONS
          predicates:
            - Path=/api/notifications/** , /websocket

springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: https://event-service.onrender.com/v3/api-docs
        name: Event Service
      - url: https://notification-service.onrender.com/v3/api-docs
        name: Notification Service            

server:
  port: ${PORT:8082}
